
CREATE DATABASE CEP;

USE CEP;

CREATE TABLE Pesquisas
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Cep VARCHAR(10) NULL,
	DataHora DATETIME NOT NULL,
)

CREATE TABLE CEPs
(
	Cep VARCHAR(10) PRIMARY KEY NOT NULL,
	Logradouro VARCHAR(200) NOT NULL,
	Bairro VARCHAR(100) NOT NULL,
	IdCidade INT NOT NULL,
)

CREATE TABLE Cidades
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdEstado INT NOT NULL,
	Nome VARCHAR(100) NOT NULL,	
)

CREATE TABLE Estados
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Sigla VARCHAR(2) NOT NULL,	
)